<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Project;
use App\Models\Trip;
use App\Models\Vehicle;
use App\Models\Employee;
use App\Models\Material;
use App\Models\Route;
use App\Models\RouteMaterial;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        $tables = ['users', 'projects', 'trips', 'vehicles', 'employees', 'materials', 'routes'];
        foreach ($tables as $table) {
            DB::table($table)->truncate();
        }

        Schema::enableForeignKeyConstraints();

        // 1. Users
        $admin = User::create([
            'name' => 'Admin',
            'email' => 'admin@transport.local',
            'password' => Hash::make('password'),
            'is_admin' => true,
        ]);
        User::create([
            'name' => 'User',
            'email' => 'user@transport.local',
            'password' => Hash::make('123456'),
            'is_admin' => false,
        ]);

        // 2. Projects (3 projects)
        $projects = [
            'San lấp mặt bằng KCN Yên Phong',
            'Xây dựng nhà xưởng Foxconn',
            'Làm đường dân sinh xã Nam Sơn',
        ];
        foreach ($projects as $name) {
            Project::create(['name' => $name, 'description' => 'Dự án thực tế 2026', 'is_active' => true]);
        }
        $projectModels = Project::all();

        // 3. Vehicles
        $vehicles = [
            ['plate' => '99C-123.45', 'vol' => 15],
            ['plate' => '29H-999.88', 'vol' => 10],
            ['plate' => '98C-567.89', 'vol' => 2],
            ['plate' => '30F-111.22', 'vol' => 20],
        ];
        foreach ($vehicles as $v) {
            Vehicle::create([
                'plate_number' => $v['plate'],
                'default_volume_m3' => $v['vol'],
                'is_active' => true
            ]);
        }
        $vehicleModels = Vehicle::all();

        // 4. Employees (Drivers)
        $drivers = [
            'Nguyễn Văn A', 'Trần Văn B', 'Lê Văn C', 'Phạm Văn D',
            'Hoàng Văn E', 'Đỗ Văn F', 'Ngô Văn G', 'Bùi Văn H'
        ];
        foreach ($drivers as $name) {
            Employee::create(['name' => $name, 'phone' => '0987654321', 'is_active' => true]);
        }
        $driverModels = Employee::all();

        // 5. Materials (Real prices)
        // Code will be auto-generated by model boot
        $materials = [
            ['name' => 'Cát vàng', 'unit' => 'm3', 'import' => 180000, 'sell' => 250000],
            ['name' => 'Cát đen san lấp', 'unit' => 'm3', 'import' => 80000, 'sell' => 120000],
            ['name' => 'Đá 1x2', 'unit' => 'm3', 'import' => 220000, 'sell' => 300000],
            ['name' => 'Đất đồi', 'unit' => 'm3', 'import' => 50000, 'sell' => 90000],
            ['name' => 'Sỏi cuội', 'unit' => 'm3', 'import' => 150000, 'sell' => 210000],
            ['name' => 'Đá hộc', 'unit' => 'm3', 'import' => 190000, 'sell' => 260000],
            ['name' => 'Cát bê tông', 'unit' => 'm3', 'import' => 250000, 'sell' => 320000],
            ['name' => 'Đất đỏ bazan', 'unit' => 'm3', 'import' => 60000, 'sell' => 110000],
        ];
        foreach ($materials as $m) {
            Material::create([
                'name' => $m['name'],
                'unit' => $m['unit'],
                'import_price' => $m['import'],
                'sell_price' => $m['sell'],
                'is_active' => true
            ]);
        }
        $materialModels = Material::all();

        // 6. Routes
        $routes = [
            ['from' => 'Mỏ cát A', 'to' => 'KCN Yên Phong', 'dist' => 15],
            ['from' => 'Mỏ đá B', 'to' => 'Nhà xưởng Foxconn', 'dist' => 25],
            ['from' => 'Bãi đất C', 'to' => 'Xã Nam Sơn', 'dist' => 5],
            ['from' => 'Cảng Tiên Sa', 'to' => 'KCN Hòa Khánh', 'dist' => 18],
            ['from' => 'Mỏ đá D', 'to' => 'Đường cao tốc Bắc Nam', 'dist' => 40],
            ['from' => 'Kho vật liệu E', 'to' => 'Khu đô thị mới', 'dist' => 12],
        ];
        foreach ($routes as $r) {
            Route::create(['from_location' => $r['from'], 'to_location' => $r['to'], 'distance_km' => $r['dist'], 'is_active' => true]);
        }
        $routeModels = Route::all();

        // 7. Trips (50 trips)
        // Distribute across projects and months (Jan, Feb, Mar 2026)
        for ($i = 0; $i < 50; $i++) {
            $project = $projectModels->random();
            $vehicle = $vehicleModels->random();
            $driver = $driverModels->random();
            $material = $materialModels->random();
            $route = $routeModels->random();
            
            // Random volume close to vehicle default
            $volume = $vehicle->default_volume_m3 * (rand(80, 110) / 100); 

            // Logic calculation
            $price_per_m3 = $material->sell_price;
            $cost_per_m3 = $material->import_price;
            $profit = ($price_per_m3 - $cost_per_m3) * $volume;
            $total_price = $price_per_m3 * $volume;

            // Random date in Jan, Feb, Mar 2026
            $month = rand(1, 3);
            $day = rand(1, 28);
            $date = sprintf('2026-%02d-%02d', $month, $day);

            Trip::create([
                'trip_date' => $date,
                'project_id' => $project->id,
                'vehicle_id' => $vehicle->id,
                'driver_id' => $driver->id,
                'material_id' => $material->id,
                'route_id' => $route->id,
                'volume_m3' => round($volume, 2),
                'price_per_m3' => $price_per_m3,
                'cost_per_m3' => $cost_per_m3,
                'profit' => $profit,
                'total_price' => $total_price,
                'note' => 'Chuyến xe tự động #' . ($i + 1),
            ]);
        }
    }
}
